# Generated by Django 3.2 on 2023-08-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom1', '0004_remove_signup_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user_id',
        ),
    ]
