# Generated by Django 3.2 on 2023-08-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom1', '0007_auto_20230821_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='artisan_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
