# Generated by Django 3.2 on 2023-08-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hom1', '0008_feedback_artisan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('feedback', models.TextField()),
            ],
            options={
                'db_table': 'artisan_feedback_table',
            },
        ),
    ]
