# Generated by Django 3.2 on 2023-08-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom1', '0010_artisanfeedback_request_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtisanFeedback',
        ),
    ]
