# Generated by Django 3.2 on 2023-08-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom1', '0011_delete_artisanfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='request',
        ),
    ]
