# Generated by Django 3.2 on 2023-08-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom1', '0012_remove_feedback_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='description',
        ),
    ]
