# Generated by Django 3.2 on 2023-08-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom1', '0013_rename_feedback_feedback_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='description',
            new_name='f_description',
        ),
    ]
