# Generated by Django 3.2 on 2023-08-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hom1', '0014_rename_description_feedback_f_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='f_description',
            new_name='feedback',
        ),
    ]
